package random;

import java.util.Random;

/**
 * A simple game, where a hero engages in battles. The hero has an equally
 * likely chance of succeeding as of failing.
 *
 * @author Nick Patrikeos + @your name
 */
public class Game {
    private Random random;

    public Game(long seed) {
        random = new Random(seed);
    }

    public Game() {
        this(System.currentTimeMillis());
    }

    public boolean battle() {
        // Return true if the hero wins, false if the hero loses.
        // The hero wins if the random number is less than 50.
        // The hero loses if the random number is greater than or equal to 50.
        // The random number is generated by calling random.nextInt(100).
        // random.nextInt(100) returns a random integer between 0 and 99.
        // so there is an equal chance of the hero winning or losing.
        // to increase the opportunity of catching 50% chance, we can use
        // random.nextInt(1000) and check if the number is less than 500.
        return random.nextInt(100) < 50;
    }

    public static void main(String[] args) {
        Game g = new Game();
        int win = 0;
        int loss = 0;
        for (int i = 0; i < 100; i++) {
            if (g.battle()) {
                win++;
                System.out.println("We won!! You are awesome!!");
            } else {
                loss++;
                System.out.println("Lost :(");
            }
        }
        System.out.println("Wins: " + win + " Losses: " + loss);
    }
}
